services:
  - type: web
    name: vwap-trading-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PORT
        generateValue: true
    healthCheckPath: /health